enum Block {
  Air = 'air',
  Iron = 'iron',
  Gold = 'gold',
  Diamond = 'diamond',
  Emerald = 'emerald',
  Copper = 'copper',
  Netherite = 'netherite',
  // Colorless = 'colorless',
  Ice = 'ice',
  Water = 'water',

  ReactorControlRod = 'reactorcontrolrod',
  FuelRod = 'fuelrod',
  ReactorCasing = 'reactorcasing',
  ReactorController = 'reactorcontroller',
  ReactorAccessPort = 'accessport',
  Graphite = 'graphite',
  Cryomisi = 'cryomisi',
  Tangerium = 'tangerium',
  Redfrigium = 'redfrigium',

  Bronze = 'bronze',
  Steel = 'steel',
  Tin = 'tin',
  Osmium = 'osmium',
  Nickel = 'nickel',
  Brass = 'brass',
  Zinc = 'zinc',
  Aluminum = 'aluminum',
  Silver = 'silver',
  Lead = 'lead',
  Platinum = 'platinum',
  Invar = 'invar',

  RefinedObsidian = 'refinedobsidian',
  RefinedGlowstone = 'refinedglowstone',
  DryIce = 'dryice',
  Cinnabar = 'cinnabar',
  Enderium = 'enderium',
  Electrum = 'electrum',
  Signalum = 'signalum',
  Lumium = 'lumium',
  Manasteel = 'manasteel',
  Elementium = 'elementium',
  Terrasteel = 'terrasteel',
  Apatite = 'apatite',
}

const BlockNames = new Map([
  [Block.Air, 'Air'],
  [Block.ReactorControlRod, 'Reactor Control Rod'],

  [Block.FuelRod, 'Reactor Fuel Rod'],
  [Block.ReactorCasing, 'Reactor Casing'],
  [Block.ReactorController, 'Reactor Controller'],
  [Block.ReactorAccessPort, 'Reactor Access Port'],

  // Solids
  [Block.Apatite, 'Apatite'],
  [Block.Cinnabar, 'Cinnabar'],
  [Block.Iron, 'Iron Block'],
  [Block.Manasteel, 'Manasteel Block'],
  [Block.Elementium, 'Elementium Block'],
  [Block.Nickel, 'Nickel Block'],
  [Block.Gold, 'Gold Block'],
  [Block.Diamond, 'Diamond Block'],
  [Block.Netherite, 'Netherite Block'],
  [Block.Terrasteel, 'Terrasteel Block'],
  [Block.Emerald, 'Emerald Block'],
  // [Block.Colorless, 'Glass'],
  [Block.Copper, 'Copper Block'],
  [Block.Brass, 'Brass Block'],
  [Block.Osmium, 'Osmium Block'],
  [Block.RefinedObsidian, 'Refined Obsidian Block'],
  [Block.RefinedGlowstone, 'Refined Glowstone Block'],
  [Block.Bronze, 'Bronze Block'],
  [Block.Zinc, 'Zinc Block'],
  [Block.Aluminum, 'Aluminum Block'],
  [Block.Steel, 'Steel Block'],
  [Block.Invar, 'Invar Block'],
  [Block.Tin, 'Tin Block'],
  [Block.Silver, 'Silver Block'],
  [Block.Signalum, 'Signalum Block'],
  [Block.Lumium, 'Lumium Block'],
  [Block.Lead, 'Lead Block'],
  [Block.Electrum, 'Electrum Block'],
  [Block.Platinum, 'Platinum Block'],
  [Block.Enderium, 'Enderium Block'],
  [Block.Graphite, 'Graphite Block'],
  [Block.Ice, 'Ice'],
  [Block.DryIce, 'Dry Ice'],

  // Liquids
  [Block.Cryomisi, 'Cryomisi'],
  [Block.Tangerium, 'Tangerium'],
  [Block.Redfrigium, 'Redfrigium'],
  [Block.Water, 'Water'],
]);

export { Block, BlockNames };
