// These are essentially all the items in crafting that are not used under build materials
enum Material {
  IronIngot = 'iron_ingot',
  GoldIngot = 'gold_ingot',
  DiamondGem = 'diamond_gem',
  EmeraldGem = 'emerald_gem',
  GraphiteIngot = 'graphite_ingot',
  SteelIngot = 'steel_ingot',
  CopperIngot = 'copper_ingot',
  TinIngot = 'tin_ingot',
  OsmiumIngot = 'osmium_ingot',
  NickelIngot = 'nickel_ingot',
  BrassIngot = 'brass_ingot',
  ZincIngot = 'zinc_ingot',
  AluminumIngot = 'aluminum_ingot',
  SilverIngot = 'silver_ingot',
  LeadIngot = 'lead_ingot',
  PlatinumIngot = 'platinum_ingot',
  InvarIngot = 'invar_ingot',
  ElectrumIngot = 'electrum_ingot',
  SignalumIngot = 'signalum_ingot',
  LumiumIngot = 'lumium_ingot',
  EnderiumIngot = 'enderium_ingot',
  BronzeIngot = 'bronze_ingot',
  ManasteelIngot = 'manasteel_ingot',
  ElementiumIngot = 'elementium_ingot',
  TerrasteelIngot = 'terrasteel_ingot',
  NetheriteIngot = 'netherite_ingot',
  RefinedObsidianIngot = 'refined_obsidian_ingot',
  RefinedGlowstoneIngot = 'refined_glowstone_ingot',
  ApatiteGem = 'apatite_gem',
  RedstoneDust = 'redstone_dust',
  NetherQuartz = 'nether_quartz',
  Stick = 'stick',
  Sand = 'sand',
  Glass = 'glass',
  WoodenPlank = 'wooden_plank',
  Cobblestone = 'cobblestone',
  Stone = 'stone',
  Chest = 'chest',
  Hopper = 'hopper',
  Comparator = 'comparator',
  Piston = 'piston',
  RedstoneTorch = 'redstone_torch',
  Uranium = 'uranium',
  UnobtainiumIngot = 'unobtainium_ingot',
  VibraniumIngot = 'vibranium_ingot',
  AllthemodiumIngot = 'allthemodium_ingot',
}

const MaterialNames = new Map([
  [Material.IronIngot, 'Iron Ingot'],
  [Material.GoldIngot, 'Gold Ingot'],
  [Material.DiamondGem, 'Diamond'],
  [Material.GraphiteIngot, 'Graphite Ingot'],
  [Material.SteelIngot, 'Steel Ingot'],
  [Material.RedstoneDust, 'Redstone Dust'],
  [Material.Stick, 'Stick'],
  [Material.Sand, 'Sand'],
  [Material.Glass, 'Glass'],
  [Material.WoodenPlank, 'Wooden Plank'],
  [Material.Cobblestone, 'Cobblestone'],
  [Material.Stone, 'Stone'],
  [Material.NetherQuartz, 'Nether Quartz'],
  [Material.Chest, 'Chest'],
  [Material.Hopper, 'Hopper'],
  [Material.Comparator, 'Comparator'],
  [Material.Piston, 'Piston'],
  [Material.Uranium, 'Uranium / Yellorium'],
  [Material.RedstoneTorch, 'Redstone Torch'],
  [Material.EmeraldGem, 'Emerald'],
  [Material.CopperIngot, 'Copper Ingot'],
  [Material.TinIngot, 'Tin Ingot'],
  [Material.OsmiumIngot, 'Osmium Ingot'],
  [Material.NickelIngot, 'Nickel Ingot'],
  [Material.BrassIngot, 'Brass Ingot'],
  [Material.ZincIngot, 'Zinc Ingot'],
  [Material.AluminumIngot, 'Aluminum Ingot'],
  [Material.SilverIngot, 'Silver Ingot'],
  [Material.LeadIngot, 'Lead Ingot'],
  [Material.PlatinumIngot, 'Platinum Ingot'],
  [Material.InvarIngot, 'Invar Ingot'],
  [Material.ElectrumIngot, 'Electrum Ingot'],
  [Material.SignalumIngot, 'Signalum Ingot'],
  [Material.LumiumIngot, 'Lumium Ingot'],
  [Material.EnderiumIngot, 'Enderium Ingot'],
  [Material.BronzeIngot, 'Bronze Ingot'],
  [Material.ManasteelIngot, 'Manasteel Ingot'],
  [Material.ElementiumIngot, 'Elementium Ingot'],
  [Material.TerrasteelIngot, 'Terrasteel Ingot'],
  [Material.NetheriteIngot, 'Netherite Ingot'],
  [Material.RefinedObsidianIngot, 'Refined Obsidian Ingot'],
  [Material.RefinedGlowstoneIngot, 'Glowstone Ingot'],
  [Material.ApatiteGem, 'Apatite Crystal'],
  [Material.AllthemodiumIngot, 'Allthemodium Ingot'],
  [Material.VibraniumIngot, 'Vibranium Ingot'],
  [Material.UnobtainiumIngot, 'Unobtainium Ingot'],
]);

export { Material, MaterialNames };
